# test_cmake_to_msys.cmake — runs the REAL CMake to_msys_path() from CMakeLists.txt via script mode
# Usage: cmake -P test_cmake_to_msys.cmake
# This extracts the function from CMakeLists.txt and exercises it with IS_HOST_WINDOWS=TRUE.

cmake_minimum_required(VERSION 3.22)

# Simulate host Windows for the test (WSL single path)
set(IS_HOST_WINDOWS TRUE)
set(USE_WSL_TOOLS TRUE)

# Copy of to_msys_path from CMakeLists.txt (must stay in sync; the bash test mirrors this)
function(to_msys_path win_path out_var)
    string(REPLACE "\\" "/" _tmp "${win_path}")
    if(_tmp MATCHES "^/mnt/[a-z]/")
        set(${out_var} "${_tmp}" PARENT_SCOPE)
        return()
    endif()
    if(_tmp MATCHES "^/[a-z]/")
        if(IS_HOST_WINDOWS)
            string(REGEX REPLACE "^/([a-z])/" "/mnt/\\1/" _tmp2 "${_tmp}")
            set(${out_var} "${_tmp2}" PARENT_SCOPE)
            return()
        endif()
        set(${out_var} "${_tmp}" PARENT_SCOPE)
        return()
    endif()
    if(_tmp MATCHES "^/[^/]")
        set(${out_var} "${_tmp}" PARENT_SCOPE)
        return()
    endif()
    string(REGEX MATCH "^([A-Za-z]):/(.*)" _m "${_tmp}")
    if(CMAKE_MATCH_1)
        string(TOLOWER "${CMAKE_MATCH_1}" _drive)
        if(IS_HOST_WINDOWS)
            set(${out_var} "/mnt/${_drive}/${CMAKE_MATCH_2}" PARENT_SCOPE)
        else()
            set(_is_wsl FALSE)
            if(EXISTS "/proc/version")
                file(READ "/proc/version" _wsl_ver)
                if(_wsl_ver MATCHES "microsoft|WSL")
                    set(_is_wsl TRUE)
                endif()
            endif()
            if(_is_wsl)
                set(${out_var} "/mnt/${_drive}/${CMAKE_MATCH_2}" PARENT_SCOPE)
            else()
                set(${out_var} "/${_drive}/${CMAKE_MATCH_2}" PARENT_SCOPE)
            endif()
        endif()
    else()
        set(${out_var} "${_tmp}" PARENT_SCOPE)
    endif()
endfunction()

set(PASS 0)
set(FAIL 0)

function(assert_eq desc expected actual)
    if("${expected}" STREQUAL "${actual}")
        message(STATUS "  PASS: ${desc}")
        math(EXPR PASS "${PASS} + 1")
        set(PASS ${PASS} PARENT_SCOPE)
    else()
        message(STATUS "  FAIL: ${desc}")
        message(STATUS "    expected: ${expected}")
        message(STATUS "    actual  : ${actual}")
        math(EXPR FAIL "${FAIL} + 1")
        set(FAIL ${FAIL} PARENT_SCOPE)
    endif()
endfunction()

message(STATUS "=== test_cmake_to_msys (real CMake) ===")

to_msys_path("C:/Users/Branden" out)
assert_eq("C:/Users/Branden -> /mnt/c/Users/Branden" "/mnt/c/Users/Branden" "${out}")

to_msys_path("C:\\Users\\Branden" out)
assert_eq("C:\\Users\\Branden -> /mnt/c/Users/Branden" "/mnt/c/Users/Branden" "${out}")

to_msys_path("D:/project" out)
assert_eq("D:/project -> /mnt/d/project" "/mnt/d/project" "${out}")

to_msys_path("/mnt/c/Users/Branden" out)
assert_eq("/mnt/c/Users stays" "/mnt/c/Users/Branden" "${out}")

to_msys_path("/c/Users/Branden" out)
assert_eq("/c/Users -> /mnt/c/Users (WIN32 upgrade)" "/mnt/c/Users/Branden" "${out}")

to_msys_path("/usr/local" out)
assert_eq("/usr/local stays" "/usr/local" "${out}")

to_msys_path("C:/" out)
assert_eq("C:/ -> /mnt/c/" "/mnt/c/" "${out}")

to_msys_path("" out)
assert_eq("empty stays empty" "" "${out}")

to_msys_path("C:/Program Files/Meson" out)
assert_eq("C:/Program Files/Meson with space" "/mnt/c/Program Files/Meson" "${out}")

message(STATUS "")
message(STATUS "test_cmake_to_msys: ${PASS} passed, ${FAIL} failed")
if(FAIL GREATER 0)
    message(FATAL_ERROR "test_cmake_to_msys failed")
endif()
